/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nova_rlopez_facedetectionopencv_OpenCvNativeClass */

#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;

#ifndef _Included_com_nova_rlopez_facedetectionopencv_OpenCvNativeClass
#define _Included_com_nova_rlopez_facedetectionopencv_OpenCvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nova_rlopez_facedetectionopencv_OpenCvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */

 int toGray(Mat img, Mat& gray);

JNIEXPORT jint JNICALL Java_com_nova_rlopez_facedetectionopencv_OpenCvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
