/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nova_rlopez_facedetectionopencv_OpencvClass */

#include <opencv2/opencv.hpp>

using namespace cv;

#ifndef _Included_com_nova_rlopez_facedetectionopencv_OpencvClass
#define _Included_com_nova_rlopez_facedetectionopencv_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nova_rlopez_facedetectionopencv_OpencvClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
 /*
JNIEXPORT jint JNICALL Java_com_nova_rlopez_facedetectionopencv_OpencvClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);
*/
/*
 * Class:     com_nova_rlopez_facedetectionopencv_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_nova_rlopez_facedetectionopencv_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
